### ISSUE TITLE
Corrupt XML binary file

### ISSUE THREAD

**Issue by mpivchev** [a-tolstykh/textview-rich-drawable#16]
This crash only happens on a physical Note 4, it works fine in emulator for some reason.

My min api is 23 so `vectorDrawables.useSupportLibrary` did not fix this.

The view:
```
<com.tolstykh.textviewrichdrawable.TextViewRichDrawable
                android:id="@+id/tv_gold"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="test"
                app:compoundDrawableHeight="14dp"
                app:compoundDrawableWidth="14dp"
                app:drawableEndVector="@drawable/ic_star" />
```

This is the error:
```
Caused by: android.view.InflateException: Binary XML file line #20: Error inflating class com.tolstykh.textviewrichdrawable.TextViewRichDrawable
        at android.view.LayoutInflater.createView(LayoutInflater.java:657)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:847)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:855)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:527)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
        at com.github.mpivchev.app.activities.Main2Activity.onCreate(Main2Activity.java:13) 
        at android.app.Activity.performCreate(Activity.java:6876) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:158) 
        at android.app.ActivityThread.main(ActivityThread.java:7225) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at android.view.LayoutInflater.createView(LayoutInflater.java:631)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:847) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:855) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:527) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
        at com.github.mpivchev.app.activities.Main2Activity.onCreate(Main2Activity.java:13) 
        at android.app.Activity.performCreate(Activity.java:6876) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:158) 
        at android.app.ActivityThread.main(ActivityThread.java:7225) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
     Caused by: android.content.res.Resources$NotFoundException: File res/drawable-xxhdpi-v4/ic_star.png from xml type xml resource ID #0x7f080075
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:4419)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:4366)
        at android.content.res.Resources.getXml(Resources.java:2421)
        at android.support.graphics.drawable.VectorDrawableCompat.create(VectorDrawableCompat.java:562)
        at com.tolstykh.textviewrichdrawable.helper.RichDrawableHelper.getVectorDrawable(RichDrawableHelper.java:157)
        at com.tolstykh.textviewrichdrawable.helper.RichDrawableHelper.inflateVectors(RichDrawableHelper.java:88)
        at com.tolstykh.textviewrichdrawable.helper.RichDrawableHelper.initCompoundDrawables(RichDrawableHelper.java:68)
        at com.tolstykh.textviewrichdrawable.helper.RichDrawableHelper.apply(RichDrawableHelper.java:59)
        at com.tolstykh.textviewrichdrawable.TextViewRichDrawable.init(TextViewRichDrawable.java:31)
        at com.tolstykh.textviewrichdrawable.TextViewRichDrawable.<init>(TextViewRichDrawable.java:21)
        at java.lang.reflect.Constructor.newInstance(Native Method) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:631) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:847) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:855) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:527) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
        at com.github.mpivchev.app.activities.Main2Activity.onCreate(Main2Activity.java:13) 
        at android.app.Activity.performCreate(Activity.java:6876) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:158) 
        at android.app.ActivityThread.main(ActivityThread.java:7225) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
     Caused by: java.io.FileNotFoundException: Corrupt XML binary file
```

**Comment by saturov** [comment]
This issue is still here on the same Xiaomi Note 4.
It works well on some simple images, but complex vector drawable with gradient leads to this crash.
