### ISSUE TITLE
Error in API 19 Kitkat devices

### ISSUE THREAD

**Issue by jamacco94** [a-tolstykh/textview-rich-drawable#17]
**Getting crash in Api 19 kitkat devices. The app crashes when used .png images, with vector images works well. 

Here is crash logs:

> `

     Caused by: android.view.InflateException: Binary XML file line #79: Error inflating class com.tolstykh.textviewrichdrawable.TextViewRichDrawable
        at android.view.LayoutInflater.createView(LayoutInflater.java:621)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:697)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:756)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:759)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
        at android.databinding.DataBindingUtil.inflate(DataBindingUtil.java:126)
        at android.databinding.DataBindingUtil.inflate(DataBindingUtil.java:95)
        at com.example.msi.winstantapp.fragments.MainFragment.onCreateView(MainFragment.java:62)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
        at android.support.v4.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2617)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2388)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2344)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3248)
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3200)
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:195)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:597)
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
        at android.app.Activity.performStart(Activity.java:5241)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2168)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
        at android.app.ActivityThread.access$800(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5017) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
        at dalvik.system.NativeStart.main(Native Method) 

>`
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.constructNative(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at android.view.LayoutInflater.createView(LayoutInflater.java:595)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:697) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:756) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:759) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
        at android.databinding.DataBindingUtil.inflate(DataBindingUtil.java:126) 
        at android.databinding.DataBindingUtil.inflate(DataBindingUtil.java:95) 
        at com.example.msi.winstantapp.fragments.MainFragment.onCreateView(MainFragment.java:62) 
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428) 
        at android.support.v4.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2617) 
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2388) 
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2344) 
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245) 
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3248) 
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3200) 
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:195) 
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:597) 
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177) 
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171) 
        at android.app.Activity.performStart(Activity.java:5241) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2168) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
        at android.app.ActivityThread.access$800(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5017) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
        at dalvik.system.NativeStart.main(Native Method) 

>`
 Caused by: android.content.res.Resources$NotFoundException: File res/drawable/flag_usd.png from xml type xml resource ID #0x7f08014e
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2361)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2316)
        at android.content.res.Resources.getXml(Resources.java:988)
        at android.support.graphics.drawable.VectorDrawableCompat.create(VectorDrawableCompat.java:562)
        at com.tolstykh.textviewrichdrawable.helper.RichDrawableHelper.getVectorDrawable(RichDrawableHelper.java:157)
        at com.tolstykh.textviewrichdrawable.helper.RichDrawableHelper.inflateVectors(RichDrawableHelper.java:82)`

**Comment by jamacco94** [comment]
The reason of crashes was VectorDrawableCompat.create(...), cuz it will only inflate vector drawables. Since we should use AppCompatDrawableManager.

So I've replaced getVectorDrawable() method with VectorDrawableCompat :
    `private VectorDrawableCompat getVectorDrawable(@DrawableRes int resId) {`
        `    return VectorDrawableCompat.create(mContext.getResources(), resId, mContext.getTheme());`
   ` }`

to the method with AppCompatDrawableManager:
   `@SuppressLint("RestrictedApi")`
    `private Drawable getVectorDrawable(@DrawableRes int resId) {`
       `     return AppCompatDrawableManager.get().getDrawable(mContext, resId);`
   ` }`
