### ISSUE TITLE
Version 0.2.1 causes application to crash for Android 4

### ISSUE THREAD

**Issue by alex-gutierrez** [a-tolstykh/textview-rich-drawable#3]
Updating to version 0.2.1 is causing application to crash in Android 4 (non vectorial support) when trying to inject the XML with TextViewRichDrawable component.

Example layout file:

Layout file, **layout/view_tag.xml**
```xml
<?xml version="1.0" encoding="utf-8"?>
<com.tolstykh.textviewrichdrawable.TextViewRichDrawable
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    app:drawableEndVector="@drawable/ic_cross"
    app:compoundDrawableHeight="10dp"
    android:drawablePadding="5dp"/>
```
Used vector icon, **drawable/ic_cross.xml**
```xml
<vector xmlns:android="http://schemas.android.com/apk/res/android"
        android:width="24dp"
        android:height="24dp"
        android:viewportWidth="24.0"
        android:viewportHeight="24.0">
    <path
        android:fillColor="#FFF"
        android:pathData="M22.245,4.015c0.313,0.313 0.313,0.826 0,1.139l-6.276,6.27c-0.313,0.312 -0.313,0.826 0,1.14l6.273,6.272c0.313,0.313 0.313,0.826 0,1.14l-2.285,2.277c-0.314,0.312 -0.828,0.312 -1.142,0l-6.271,-6.271c-0.313,-0.313 -0.828,-0.313 -1.141,0l-6.276,6.267c-0.313,0.313 -0.828,0.313 -1.141,0l-2.282,-2.28c-0.313,-0.313 -0.313,-0.826 0,-1.14l6.278,-6.269c0.313,-0.312 0.313,-0.826 0,-1.14L1.709,5.147c-0.314,-0.313 -0.314,-0.827 0,-1.14l2.284,-2.278C4.308,1.417 4.821,1.417 5.135,1.73L11.405,8c0.314,0.314 0.828,0.314 1.141,0.001l6.276,-6.267c0.312,-0.312 0.826,-0.312 1.141,0L22.245,4.015z"/>
</vector>
```

When trying to inflate the class, it causes application to crash since for Android 4 vector drawables are converted to PNG at compile time:

```
android.view.InflateException: Binary XML file line #2: Error inflating class com.tolstykh.textviewrichdrawable.TextViewRichDrawable
	at android.view.LayoutInflater.createView(LayoutInflater.java:620)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:469)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
	at android.view.View.inflate(View.java:17949)
	at com.myapp.views.TagView.<init>(TagView.java:25)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.constructNative(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at android.view.LayoutInflater.createView(LayoutInflater.java:594)
	... 83 more
Caused by: android.content.res.Resources$NotFoundException: File res/drawable-hdpi-v4/ic_cross.png from xml type xml resource ID #0x7f0200b1
	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2412)
	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2367)
	at android.content.res.Resources.getXml(Resources.java:998)
	at android.support.v7.widget.ResourcesWrapper.getXml(ResourcesWrapper.java:183)
	at android.support.graphics.drawable.VectorDrawableCompat.create(VectorDrawableCompat.java:586)
	at com.tolstykh.textviewrichdrawable.TextViewRichDrawable.getVectorDrawable(TextViewRichDrawable.java:160)
	at com.tolstykh.textviewrichdrawable.TextViewRichDrawable.initCompoundDrawables(TextViewRichDrawable.java:85)
	at com.tolstykh.textviewrichdrawable.TextViewRichDrawable.init(TextViewRichDrawable.java:68)
	at com.tolstykh.textviewrichdrawable.TextViewRichDrawable.<init>(TextViewRichDrawable.java:39)
	... 86 more
Caused by: java.io.FileNotFoundException: Corrupt XML binary file
	at android.content.res.AssetManager.openXmlAssetNative(Native Method)
	at android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:501)
	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2394)
	... 94 more
```

**Comment by a-tolstykh** [comment]
Hello @alex-gutierrez . Thank you for your report.
I missed one line in documentation and will update it today.

In order to use the library, you need to [enable vector support](https://developer.android.com/guide/topics/graphics/vector-drawable-resources.html#vector-drawables-backward-solution) for Android versions lower than 5.
Add next line to your application's `gradle.build` file:
```
 android {
   defaultConfig {
     vectorDrawables.useSupportLibrary = true
    }
 }
```
Let me know if it is solved your issue.

**Comment by a-tolstykh** [comment]
Documentation has been updated.
